from .GCN_model2 import *
from .GCN_model2_act import *
from .GCN_model2_bn import *
from .GCN_model3 import *
from .GCN_model3_bn import *
from .GCN_model4 import *
from .GCN_OGB import *
from .Graphsage_OGB import *
from .GAT_model2 import *
from .GAT_model2_bn import *
from .GAT_model3 import *
from .Graphsage_model2 import *
from .Graphsage_model2_bn import *
from .Graphsage_model3 import *
from .GAT_OGB import *